apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
spec:
  selector:
    app: nginx-exporter  # Assurez-vous que c'est le même que dans le Deployment nginx-exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
  type: LoadBalancer  # Changez en NodePort ou LoadBalancer si nécessaire