apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          ports:
            - containerPort: 9104
          resources:
            limits:
              cpu: "200m" # Limite CPU de 200 milli-CPU (0,2 CPU)
              memory: "256Mi" # Limite mémoire de 256 MiB
            requests:
              cpu: "100m" # Demande CPU de 100 milli-CPU (0,1 CPU)
              memory: "128Mi" # Demande mémoire de 128 MiB
          env:
            - name: DATA_SOURCE_NAME
              value: "root:your_mysql_root_password_here@(mysql:3306)/your_mysql_database_name_here"
