apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        protocol: TCP
        resources:
          limits:
            cpu: "100m" # Limite CPU de 100 milli-CPU (0,1 CPU)
            memory: "128Mi" # Limite mémoire de 128 MiB
          requests:
            cpu: "50m" # Demande CPU de 50 milli-CPU (0,05 CPU)
            memory: "64Mi" # Demande mémoire de 64 MiB